apiVersion: v1
kind: Service
metadata:
  name: {{ template "better-db.fullname" . }}
  labels:
    app: {{ template "better-db.name" . }}
    chart: {{ template "better-db.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 443
      targetPort: 8443
      protocol: TCP
      name: tls-port
    - port: 9200
      targetPort: 9200
      protocol: UDP
      name: udp-port
  selector:
    app: {{ template "better-db.name" . }}
    release: {{ .Release.Name }}
